[env]

RUST_LOG="backend=debug"

RTJAM_DATABASE_URL="postgres://postgres:postgres@localhost/postgres?sslmode=disable"
RTJAM_LISTEN_ADDRESS="0.0.0.0:3000"
RTJAM_SESSION_KEY="mN1GR7dsQ+Bj8NFIA+n/uvSbBcdyvHnVdFuJSJrQJ3g2/8gGYaATt3Wv7j3xKpD07652no/eddRdD7sJTVjg4w=="
RTJAM_NATS_URL="localhost:4222"

RTJAM_SMTP_HOST="mail.privateemail.com"
RTJAM_SMTP_PORT="587"
RTJAM_SMTP_USER="info@capass.org"
RTJAM_SMTP_PASSWORD=""
RTJAM_SMTP_FROM="info@capass.org"

RTJAM_APP_URL="http://localhost:8080"

RTJAM_WEBTRANSPORT_ADDRESS="0.0.0.0:4433"
RTJAM_CERT_PATH="backend/certs/localhost.dev.pem"
RTJAM_KEY_PATH="backend/certs/localhost.dev.key"
