[env]

RUST_LOG="backend=debug"


RTJAM_WEBTRANSPORT_PORT="42069"

RTJAM_DATABASE_URI="postgres://postgres:postgres@localhost/postgres?sslmode=disable"
RTJAM_LISTEN_ADDRESS="0.0.0.0:3000"
RTJAM_SESSION_KEY="mN1GR7dsQ+Bj8NFIA+n/uvSbBcdyvHnVdFuJSJrQJ3g2/8gGYaATt3Wv7j3xKpD07652no/eddRdD7sJTVjg4w=="

RTJAM_SMTP_HOST="mail.privateemail.com"
RTJAM_SMTP_PORT="587"
RTJAM_SMTP_USER="info@capass.org"
RTJAM_SMTP_PASSWORD="@info-Alarmfox97"
RTJAM_SMTP_FROM="info@capass.org"
